module.exports = [
  { front: 'Isaiah 9:6', back: 'For to us a child is born, to us a son is given, and the government will be on his shoulders. And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.' },
  { front: 'Isaiah 40:28', back: 'Do you not know? Have you not heard? The Lord is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary, and his understanding no one can fathom.' },
  { front: 'Genesis 1:1', back: 'In the beginning God created the heavens and the earth.' },
  { front: 'John 3:16-17', back: 'For God so loved the world that He gave His one and only Son, that whoever believes in Him shall not perish but have eternal life. For God did not send His Son into the world to condemn the world, but to save the world through Him.' },
  { front: 'Romans 3:23', back: 'For all have sinned and fall short of the glory of God.' },
  { front: 'Romans 6:23', back: 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.' },
  { front: 'Revelation 3:20', back: 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with him, and he with me.' },
  { front: 'John 14:6', back: 'Jesus answered, "I am the way and the truth and the life. No one comes to the father except through me."' },
  { front: 'Ephesians 2:8-9', back: 'For it is by grace you have been saved, through faith—and this not from yourselves, it is the gift of God—not by works, so that no one can boast.' },
  { front: '2 Corinthians 5:17', back: 'Therefore, if anyone is in Christ he is a new creation; the old has gone, the new has come!' },
  { front: 'Romans 8:28', back: 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.' },
  { front: 'Isaiah 40:30-31', back: 'Even youths grow tired and weary, and young men stumble and fall; but those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.' },
  { front: 'Romans 8:38-39', back: 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.' },
  { front: 'Matthew 11:28-30', back: 'Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls. For my yoke is easy and my burden is light.' },
  { front: 'Psalm 27:1', back: 'The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid?' },
  { front: 'Jeremiah 29:11', back: '"For I know the plans I have for you," declares the Lord, "plans to prosper you and not to harm you, plans to give you hope and a future."' },
  { front: 'Hebrews 13:8', back: 'Jesus Christ is the same yesterday and today and forever.' },
  { front: '2 Peter 3:9', back: 'The Lord is not slow in keeping His promise, as some understand slowness. He is patient with you, not wanting anyone to perish, but everyone to come to repentance.' },
  { front: 'Lamentations 3:22-23', back: "Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness." },
  { front: '2 Corinthians 12:9', back: 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ\'s power may rest on me.' },
  { front: '2 Corinthians 4:18', back: 'So we fix our eyes not on what is seen, but on what is unseen. For what is seen is temporary, but what is unseen is eternal.' },
  { front: 'Psalm 37:4-5', back: 'Delight yourself in the Lord and he will give you the desires of your heart. Commit your way to the Lord, trust in him and he will do this.' },
  { front: 'Proverbs 3:5-7', back: 'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways acknowledge him, and he will make your paths straight.' },
  { front: 'Philippians 4:13', back: 'I can do all things through Christ who strengthens me.' },
  { front: 'Galatians 2:20', back: 'I have been crucified with Christ and I no longer live, but Christ lives in me. The life I live in the body, I live by faith in the Son of God, who loved me and gave himself for me.' },
  { front: 'James 1:22', back: 'Do not merely listen to the word, and so deceive yourselves. Do what it says.' },
  { front: 'Colossians 3:23', back: 'Whatever you do, work at it with all your heart, as working for the Lord, not for men.' },
  { front: '1 Corinthians 15:58', back: 'Therefore, my dear brothers, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.' },
  { front: 'James 4:7', back: 'Submit yourselves, then, to God. Resist the devil, and he will flee from you.' },
  { front: 'Luke 16:13', back: 'No servant can serve two masters. Either he will hate the one and love the other, or he will be devoted to the one and despise the other. You cannot serve both God and Money.' },
  { front: '1 John 4:7-8', back: 'Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God. Whoever does not love does not know God, because God is love.' },
  { front: 'Galatians 5:22-23', back: 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law.' },
  { front: 'Hebrews 12:1-2', back: 'Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles, and let us run with perseverance the race marked out for us. Let us fix our eyes on Jesus, the author and perfecter of our faith, who for the joy set before Him endured the cross, scorning its shame, and sat down at the right hand of the throne of God.' },
  { front: 'Acts 1:8', back: 'But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.' },
  { front: 'Romans 12:1-2', back: "Therefore, I urge you, brothers, in view of God's mercy, to offer your bodies as living sacrifices, holy and pleasing to God—this is your spiritual act of worship. Do not conform any longer to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is—his good, pleasing and perfect will." },
  { front: '1 Thessalonians 5:18', back: "Give thanks in all circumstances, for this is God's will for you in Christ Jesus." },
  { front: 'Psalm 19:14', back: 'May the words of my mouth and the meditation of my heart be pleasing in your sight, O Lord, my Rock and my Redeemer.' },
  { front: 'Philippians 4:6-7', back: 'Do not be anxious about anything, but in everything, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.' },
  { front: '2 Timothy 3:16', back: 'All Scripture is God-breathed and is useful for teaching, rebuking, correcting, and training in righteousness.' },
  { front: 'Psalm 119:105', back: 'Your word is a lamp to my feet and a light for my path.' },
  { front: 'Psalm 119:11', back: 'I have hidden your word in my heart that I might not sin against you.' },
  { front: 'Hebrews 4:16', back: 'Let us then approach the throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.' },
  { front: '1 John 1:9', back: 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.' },
  { front: 'James 5:16', back: 'Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous man is powerful and effective.' },
  { front: '1 Corinthians 10:13', back: 'No temptation has seized you except what is common to man. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out, so that you can stand up under it.' },
  { front: 'Micah 6:8', back: 'He has showed you, O man, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.' },
  { front: 'Matthew 25:40', back: 'The King will reply, "I tell you the truth, whatever you did for one of the least of these brothers of mine, you did for me."' },
  { front: 'Matthew 28:19-20', back: 'Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age.' },
  { front: 'Matthew 5:16', back: 'In the same way, let your light shine before men, that they may see your good deeds and praise your Father in heaven.' },
  { front: 'Ephesians 6:12', back: 'For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.' },
];
